package miniJava.SyntacticAnalyzer;


public enum TokenKind {KEYWORD, ID, EOT, RBOX, LBOX, RBRACK,
						LBRACK, COMMA, LPAREN, RPAREN, PERIOD, 
						EQUALS, SEMI, UNOP, BINOP, NUM, ERROR,
						CLASS, BOOLEAN, PUBLIC, PRIVATE, STATIC, 
						INT, IF, WHILE, ELSE, THIS, NEW, RETURN, 
						TRUE, FALSE, VOID, COMMENT, OPENCOMMENT, CLOSECOMMENT, DUALOP}

